#!/usr/bin/env bash
# Score every implementation in runs/<spec>-*/{A,B,C}-*/ against the canonical
# rubric, write per-run JSON, then aggregate to rubric-<spec>.md.
#
# Usage:
#   ./harness/score-rubric.sh <spec>     # e.g. rate-limiter
#
# Per impl: resolves the RateLimiter import path, copies the rubric test file
# into tests/, runs vitest --reporter=json 3× for majority verdict per testname,
# writes .harness/rubric-score.json, cleans up the temp test file.

set -euo pipefail

SPEC="${1:-}"
[[ -z "$SPEC" ]] && { echo "usage: $0 <spec>" >&2; exit 2; }

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
RUBRIC_SRC="$ROOT/rubric/$SPEC.round2.test.ts"
[[ -f "$RUBRIC_SRC" ]] || { echo "missing rubric file: $RUBRIC_SRC" >&2; exit 2; }

# Resolve impl import path. Looks for a src file that exports the expected symbol
# matching $RUBRIC_SYMBOL. Returns "../src/<basename>" style.
resolve_import() {
  local dir="$1"
  for f in "$dir"/src/*.ts; do
    [[ -f "$f" ]] || continue
    local base
    base=$(basename "$f" .ts)
    # Skip pure index re-exports; prefer the file with the actual definition.
    if grep -qE "export (function|class|const|let|var|async function) +$RUBRIC_SYMBOL\b" "$f"; then
      echo "../src/$base"
      return 0
    fi
  done
  # Fallback: index.ts re-exports it.
  if [[ -f "$dir/src/index.ts" ]] && grep -qE "\b$RUBRIC_SYMBOL\b" "$dir/src/index.ts"; then
    echo "../src/index"
    return 0
  fi
  return 1
}

# Symbol the rubric test imports — used by resolve_import.
case "$SPEC" in
  rate-limiter) RUBRIC_SYMBOL="RateLimiter" ;;
  csv-parser)   RUBRIC_SYMBOL="parse" ;;
  retry)        RUBRIC_SYMBOL="retry" ;;
  *)            RUBRIC_SYMBOL="" ;;
esac
[[ -z "$RUBRIC_SYMBOL" ]] && { echo "unknown spec: $SPEC (extend RUBRIC_SYMBOL switch)" >&2; exit 2; }

# Score one run dir. Echoes the path to the resulting rubric-score.json.
score_one() {
  local dir="$1"
  local rel="${dir#$ROOT/}"
  local label="$rel"
  local test_file="$dir/tests/_rubric.test.ts"
  local info_file="$dir/.harness/rubric-info.json"
  local scores_file="$dir/.harness/rubric-score.json"

  rm -f "$test_file" "$info_file"

  local import_path
  if ! import_path=$(resolve_import "$dir"); then
    printf '{"label":"%s","interface_compat":false,"reason":"no RateLimiter export found"}\n' "$label" > "$scores_file"
    echo "  [skip] $label — no compatible export"
    return 0
  fi

  # Stage the rubric test file with import path substituted.
  sed "s|__IMPL_IMPORT__|$import_path|g" "$RUBRIC_SRC" > "$test_file"

  # Run 3× for majority verdict.
  local merged="$dir/.harness/rubric-runs.json"
  rm -f "$merged"
  : > "$merged"
  for run in 1 2 3; do
    local out="$dir/.harness/rubric-vitest-$run.json"
    (
      cd "$dir"
      RUBRIC_INFO_PATH="$info_file" npx vitest run tests/_rubric.test.ts \
        --reporter=json --outputFile="$out" >/dev/null 2>&1 || true
    )
    [[ -f "$out" ]] || { echo "  [warn] $label run $run produced no output"; continue; }
    cat "$out" >> "$merged"
    echo >> "$merged"
  done

  # Aggregate test results: for each test fullName, majority pass/fail across the 3 runs.
  local info_json="null"
  [[ -f "$info_file" ]] && info_json=$(cat "$info_file")

  jq -s --arg label "$label" --argjson info "$info_json" '
    def results: [.[] | .testResults[]? | .assertionResults[]? | {name: .fullName, status}];
    (results | group_by(.name) | map({
      name: .[0].name,
      passes: ([.[] | select(.status == "passed")] | length),
      runs: length,
      verdict: (if ([.[] | select(.status == "passed")] | length) > (length / 2) then "pass" else "fail" end)
    })) as $tests |
    {
      label: $label,
      interface_compat: true,
      tests: $tests,
      passed: ($tests | map(select(.verdict == "pass")) | length),
      total: ($tests | map(select(.name | startswith("informational") | not)) | length),
      pass_count: ($tests | map(select(.verdict == "pass" and (.name | startswith("informational") | not))) | length),
      info: $info
    }
  ' "$merged" > "$scores_file"

  local p=$(jq -r '.pass_count' "$scores_file")
  local t=$(jq -r '.total' "$scores_file")
  echo "  [score] $label  $p/$t"
}

# ---- main
echo "Scoring $SPEC..."
DIRS=()
while IFS= read -r line; do DIRS+=("$line"); done < <(ls -d "$ROOT/runs/$SPEC"-*/[ABC]-*/ 2>/dev/null | sort)
[[ ${#DIRS[@]} -eq 0 ]] && { echo "no run dirs found for $SPEC" >&2; exit 1; }

for d in "${DIRS[@]}"; do
  score_one "${d%/}"
done

# ---- aggregate to markdown
AGG="$ROOT/rubric-$SPEC.md"
{
  echo "# Rubric — $SPEC"
  echo
  echo "Auto-generated by \`harness/score-rubric.sh $SPEC\`. Each impl scored against \`rubric/$SPEC.round2.test.ts\` via 3 vitest runs with majority verdict per test."
  echo
  echo "## Headline"
  echo
  echo "| Condition | n | mean pass | mean total | mean ratio |"
  echo "|-----------|---|-----------|------------|------------|"
  for cond in A B C; do
    rows=()
    for d in "${DIRS[@]}"; do
      [[ "$d" == *"/$cond-"* ]] && rows+=("$d.harness/rubric-score.json")
    done
    stats=$(jq -s '
      map(select(.interface_compat == true)) as $ok
      | {n: ($ok | length),
         mp: (if ($ok|length)>0 then (($ok|map(.pass_count)|add) / ($ok|length)) else 0 end),
         mt: (if ($ok|length)>0 then (($ok|map(.total)|add) / ($ok|length)) else 0 end)}
      | "\(.n)|\(.mp)|\(.mt)"
    ' "${rows[@]}" 2>/dev/null || echo "0|0|0")
    n=$(echo "$stats" | tr -d '"' | cut -d'|' -f1)
    mp=$(echo "$stats" | tr -d '"' | cut -d'|' -f2)
    mt=$(echo "$stats" | tr -d '"' | cut -d'|' -f3)
    ratio=$(awk -v p="$mp" -v t="$mt" 'BEGIN{ if (t>0) printf "%.3f", p/t; else print "n/a" }')
    printf "| %s | %s | %.2f | %.2f | %s |\n" "$cond" "$n" "$mp" "$mt" "$ratio"
  done
  echo
  echo "## Per-test pass rate by condition"
  echo
  # Collect every test name across all scored runs.
  all_jsons=$(printf '%s\n' "${DIRS[@]}" | sed 's|$|.harness/rubric-score.json|')
  test_names=$(jq -r '.tests[]?.name' $all_jsons 2>/dev/null | sort -u)
  echo "| Test | A | B | C |"
  echo "|------|---|---|---|"
  while IFS= read -r tname; do
    [[ -z "$tname" ]] && continue
    row="| $tname |"
    for cond in A B C; do
      pass=0; total=0
      for d in "${DIRS[@]}"; do
        [[ "$d" == *"/$cond-"* ]] || continue
        sf="$d.harness/rubric-score.json"
        [[ -f "$sf" ]] || continue
        v=$(jq -r --arg n "$tname" '.tests[]? | select(.name == $n) | .verdict' "$sf" 2>/dev/null)
        [[ -z "$v" ]] && continue
        total=$((total + 1))
        [[ "$v" == "pass" ]] && pass=$((pass + 1))
      done
      row="$row $pass/$total |"
    done
    echo "$row"
  done <<< "$test_names"
  echo
  echo "## Interface compatibility"
  echo
  echo "| Run | Compatible |"
  echo "|-----|------------|"
  for d in "${DIRS[@]}"; do
    sf="$d.harness/rubric-score.json"
    [[ -f "$sf" ]] || continue
    compat=$(jq -r '.interface_compat' "$sf")
    label=$(jq -r '.label' "$sf")
    printf "| %s | %s |\n" "$label" "$compat"
  done
} > "$AGG"

echo
echo "Wrote $AGG"
